### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by luca-nardelli** [api-platform/api-doc-parser#50]
I've tried to run the command through `npx` on my machine but it doesn't work.
```
$ npx @api-platform/client-generator
npx: installed 284 in 10.132s
Cannot find module 'lodash'
```
If I install the package globally I get the following error

```bash
$ generate-api-platform-client 
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/luca/.nvm/versions/node/v11.10.0/lib/node_modules/@api-platform/client-generator/node_modules/@api-platform/api-doc-parser/lib/swagger/handleJson.js:48:15)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
```

However, I can solve this by globally installing `lodash`

**Comment by luca-nardelli** [comment]
Yeah I'll do that!

**Comment by luca-nardelli** [comment]
Opened the PR: https://github.com/api-platform/api-doc-parser/pull/51

I had to add `lodash.uniq` as a dependency and also change how the two functions were imported, since `lodash` is not listed in the package.json
